// <auto-generated/>

using System;
using System.Collections.Generic;
using System.Text;

namespace External.ServiceModel.Configuration.Test.Contract
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute()]
    public interface ITestService
    {

        [System.ServiceModel.OperationContractAttribute()]
        string TesMethod(string test);

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ITestServiceChannel : ITestService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class TestServiceClient : System.ServiceModel.ClientBase<ITestService>, ITestService
    {

        public TestServiceClient()
        {
        }

        public TestServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public TestServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public TestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public TestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public string TesMethod(string test)
        {
            return base.Channel.TesMethod(test);
        }
    }
}
